use_frameworks!

target 'YHLog_Example' do
  pod 'YHLog', :path => '../'

  target 'YHLog_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
